### ISSUE TITLE
Installation issue on Unix

### ISSUE THREAD

**Issue by cuperusj** [plantformatics/Socrates#1]
R 4.0.5, Mac 11.2.3 (Big Sur), freshly updated R studio:
Library(devtools)
install_github("plantformatics/Socrates")
Downloading GitHub repo plantformatics/Socrates@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/plantformatics/Socrates/tarball/HEAD' failed

I then downloaded and and successfully installed locally with install_local

install_local("/Users/cuperusj/Downloads/Socrates-main.zip")

**Comment by plantformatics** [comment]
I updated the dependencies and package versions which should fix this problem (at least for Unix users). Thanks for letting us know.
