### ISSUE TITLE
Clarification on cell filtering

### ISSUE THREAD

**Issue by IsaacDiaz026** [plantformatics/Socrates#15]
Hey Alex,

I would like to extract cell barcodes for only cells that pass filtering criteria. I notice that after running using the findCells function as performed in the tutorial, it produces obj$meta.v1, obj$meta.v2, and obj$meta.v3.

Which of these dataframes represent that cells that passed all of the filtering steps?

**Comment by plantformatics** [comment]
The slot ‘meta.v3’ will contain the filtered cell barcodes. I would also encourage you to have a look at a new function called `isCell` which will remove barcodes with chromatin accessibility profiles that resemble background (empty droplets that contain broken DNA). There isn’t documentation yet,  yet you can check out the arguments entering `?isCell` at the prompt.

**Comment by IsaacDiaz026** [comment]
Hi Alex,

I tried out the isCell function to filter barcodes. For some reason it returns all NAs for the "background" and "is_cell" columns. I ran the callACRs, buildMetaData, findCells, and generateMatrix functions as specified in the tutorial. One difference is that I do not have plastid and mitochondrial scaffolds included. 

I have attached a subset of the output for the isCell function. 
[subset_isCell.txt](https://github.com/plantformatics/Socrates/files/10539340/subset_isCell.txt)

**Comment by plantformatics** [comment]
Hi Isaac,

Can you try running the same pipeline but with out "findCells"? All it should need is buildMetaData and generateMatrix before hand. Sounds like we need more checks in place for ensuring pipeline compatibility...

**Comment by IsaacDiaz026** [comment]
Hi Alex, 

I have tried this pipeline without findCells and had no luck. I believe the size of the input fragments file may be too large? The fragments file is 171,275,344 lines long. When subsetting this file, the isCell function appears to work just fine. I am using 900G of RAM, but there are not any error messages that would suggest I am running out of memory. 

Is there a logical way of splitting up the fragments file so that I can process it in pieces? Or is the entire file necessary for calculating the background? 

Sorry for the delay, I have been stuck in a long queue for computing resources.

**Comment by plantformatics** [comment]
Can you paste the error message that you receive when using the full fragment file? I have used Socrates with 2-3x as many lines without issue - that shouldn't be a problem. All the chromosome name match between your fai reference and bed/tsv file?

**Comment by plantformatics** [comment]
A quick look at the output shows that the comparison to the background bulk failed (NA populated column). What are the counts distribution (knee plot) for your data? I wonder if the 100 integrations threshold needs to be adjusted specifically for your data.

**Comment by IsaacDiaz026** [comment]
Hi Alex,

The isCell command runs with no errors, here is the message converting triplet format to sparseMatrix
 - setting filters
 - parsing initial boundaries
 - normalizing distributions and creating references
 - performing feature selection (this step is a bottle-neck and may take a while to complete)
 - estimating correlations

The chromosome names do match between my fragments file and my fai reference, but there are 17 small scaffolds that are not present in the fragments file. 
[Floral_scATAC_qual_ALLcells.QC_FIGURES.pdf](https://github.com/plantformatics/Socrates/files/10750575/Floral_scATAC_qual_ALLcells.QC_FIGURES.pdf)


I have attached the QC pdf here

**Comment by plantformatics** [comment]
And you’re sure that cells haven’t been filtered at all? IsCell needs barcodes to build the background model. What is the output of ‘ncol(obj$counts)’?

**Comment by plantformatics** [comment]
Looks like many cells are filtered in the QC plot. You’ll typically have 500-700k barcodes in sparse matrix that aren’t showing up in the knee plot.

**Comment by IsaacDiaz026** [comment]
I have not filtered the cells, the dimensions of obj$counts is 3 columns, 99109330 rows.  

Here is a subset of obj$counts:

 V1                           V2 V3
1 scaffold_1_1_1000 TGATGCACAAATAGTG-Cclementina  1
2 scaffold_1_1_1000 GAAGTGGTCCGAGAGA-Cclementina  1
3 scaffold_1_1_1000 GAGGCTCTCCCACTTG-Cclementina  1
4 scaffold_1_1_1000 AACTTGGAGAGGAATG-Cclementina  1
5 scaffold_1_1_1000 CGCAATATCGTCCCAT-Cclementina  1
7 scaffold_1_1_1000 GAGCGCTTCATTCGGA-Cclementina  1

**Comment by plantformatics** [comment]
That explains it - the counts matrix needs to be in sparse matrix format. Hold out for push

**Comment by plantformatics** [comment]
One more question - can you share `nrow(obj$meta)` and `head(obj$meta)`?

**Comment by IsaacDiaz026** [comment]
After generateMatrix : obj$meta is 7 columns with 20664 rows

 cellID  total    tss   acrs ptmt nSites log10nSites
TGATGCACAAATAGTG-Cclementina TGATGCACAAATAGTG-Cclementina 173195  79035  83159   NA  59291    4.772989
GAAGTGGTCCGAGAGA-Cclementina GAAGTGGTCCGAGAGA-Cclementina 419625 197173 205675   NA 107395    5.030984
GAGGCTCTCCCACTTG-Cclementina GAGGCTCTCCCACTTG-Cclementina 650427 292526 298129   NA 153103    5.184984
AACTTGGAGAGGAATG-Cclementina AACTTGGAGAGGAATG-Cclementina 160501  73998 101624   NA  48739    4.687877
CGCAATATCGTCCCAT-Cclementina CGCAATATCGTCCCAT-Cclementina 843290 413481 460806   NA 158124    5.198998
GAGCGCTTCATTCGGA-Cclementina GAGCGCTTCATTCGGA-Cclementina  90443  40306  54539   NA  28753    4.458683

**Comment by plantformatics** [comment]
Alright I think I got it - when you run `generateMatrix` can you set the parameter `filtered=F`? I just changed the default from TRUE to FALSE to avoid confusion in the future.

**Comment by IsaacDiaz026** [comment]
I have already been using filtered = F, here is the command I have been using .
obj <- generateMatrix(obj, filtered=F, windows=1000, peaks=F, verbose=T)

I am not sure if this is the issue, isCell seems to work fine on a random subset of 1million lines from the fragments file. here is the output of isCell using this subset of data.
[socrates_subset_output.txt](https://github.com/plantformatics/Socrates/files/10771881/socrates_subset_output.txt)

**Comment by plantformatics** [comment]
There is a line in the `isCell` that forces the sparse matrix and meta data to contain the same barcodes. If your meta data is already filtered (it looks like it is given `nrow(obj$meta) = 20664 rows)`, then the function will not be able to make a background model and the column will be populated with NAs. 

Can you share your pipeline? Feel free to send over email (marand at uga dot edu). There is something happening upstream that is incompatible with `isCell`. Thanks for your help.

**Comment by IsaacDiaz026** [comment]
Hi Alex,

Just wanted to update you on this. I ran cell-ranger ATAC with the original fastqs and then used the generated fragments file as input to Socrates. It worked like a charm! Thank you for your help!

**Comment by plantformatics** [comment]
Awesome - thanks for helping to troubleshoot this!
