### ISSUE TITLE
Regressing out effect of Genotype

### ISSUE THREAD

**Issue by IsaacDiaz026** [plantformatics/Socrates#16]
Hi Alex,

I was wondering if it is possible to regress out the effect of genotype using the regModel command with the "variates" option specified. I have performed genetic demultiplexing to assign cell barcodes to 1 of 20 different genotypes. 

Could I add a column to "meta" that specifies the cell's genotype? Or do I need to one-hot encode each genotype as a separate factor in meta and include each of these factors in the "variates" option?

**Comment by plantformatics** [comment]
Adding a single column with genotype should work fine. Alternatively, you could also use something like Harmony on the SVD/PCA embedding to correct for genotype effects. It’s worth exploring both options to see what gives better results for your data set.
