### ISSUE TITLE
how to merge Socrates object

### ISSUE THREAD

**Issue by xmliu01** [plantformatics/Socrates#18]
If I have several snATAC-seq library which are from different development stages, and I want to combine these data, how to merge Socrates object?

**Comment by plantformatics** [comment]
The easiest way is to concatenate the fragments.tsv or Tn5.bed files, then sort (`sort -k1,1 -k2,2n`), prior to loading into Socrates. There is another way to merge objects downstream, but it is a little more involved. How big are your input files?

**Comment by xmliu01** [comment]
I have 20 fragments.tsv.gz and I want to merge them into one fragments.tsv. But there is another error when I use the Socrates. "Error: cons memory exhausted (limit reached?)" I think that maybe because the fragment.tsv is too big. The size of this fragment.tsv.gz is 2.6G.

**Comment by plantformatics** [comment]
I added a new function called `mergeSocObjects` that takes a list of soc objects as input to the latest commit. Can you let me know if that solves this issue?

**Comment by xmliu01** [comment]
Hi Alex, I tried merging objects with `mergeSocObjects` and it worked, thanks a lot.
