### ISSUE TITLE
buildMetaData

### ISSUE THREAD

**Issue by werhmk** [plantformatics/Socrates#2]
Hi,
When I run the command "obj <- buildMetaData(obj, tss.window=2000, verbose=TRUE)", it received a error message as followed:
"Error in .local(x, ...) : strand values must be in '+' '-' '*'.  ",
Is the format of GFF file incorrect?  But I have check the obj$gff, only the "+" and "-" can be print.  
Could you give some suggestions to fix this problem?

Best,
MK

**Comment by plantformatics** [comment]
Hi MK,

I've never seen that error before. Can you share the first few lines of the BED and GFF input files?

**Comment by werhmk** [comment]
Hi,

This is the Bed file from the output of CellRanger-atac count (the fragments.tsv.gz), like:
Chr1	1840531	1840625	CTGCGTTCAAGACACG-1	2
Chr1	1840537	1840775	ATTGTGGCAGTGGTCC-1	1
Chr1	1840541	1840890	ACGTGGCAGGGACGTT-1	1
Chr1	1840585	1840780	CTCTAGCCAGTTACAC-1	1
Chr1	1840593	1840626	TGACAACAGCGCGTTC-1	1

and this is the first gene info from the GFF3 file:
Chr1    phytozomev11    gene    2903    10817   .       +       .       ID=LCD_CLX01G00001.V1;Name=LCD_CLX01G00001
Chr1    phytozomev11    mRNA    2903    10817   .       +       .       ID=LCD_CLX01G00001.1.V1;Name=LCD_CLX01G00001.1;pacid=33123311;longest=1;Parent=LCD_CLX01G00001.V1
Chr1    phytozomev11    five_prime_UTR  2903    3268    .       +       .       ID=LCD_CLX01G00001.1.V1.five_prime_UTR.1;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    five_prime_UTR  3354    3448    .       +       .       ID=LCD_CLX01G00001.1.V1.five_prime_UTR.2;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    CDS     3449    3616    .       +       0       ID=LCD_CLX01G00001.1.V1.CDS.1;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    CDS     4357    4455    .       +       0       ID=LCD_CLX01G00001.1.V1.CDS.2;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    CDS     5457    5560    .       +       0       ID=LCD_CLX01G00001.1.V1.CDS.3;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    CDS     7136    7944    .       +       1       ID=LCD_CLX01G00001.1.V1.CDS.4;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    CDS     8028    8150    .       +       2       ID=LCD_CLX01G00001.1.V1.CDS.5;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    CDS     8232    8320    .       +       2       ID=LCD_CLX01G00001.1.V1.CDS.6;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    CDS     8408    8608    .       +       0       ID=LCD_CLX01G00001.1.V1.CDS.7;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    CDS     9210    9617    .       +       0       ID=LCD_CLX01G00001.1.V1.CDS.8;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    CDS     10104   10187   .       +       0       ID=LCD_CLX01G00001.1.V1.CDS.9;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    CDS     10274   10297   .       +       0       ID=LCD_CLX01G00001.1.V1.CDS.10;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    three_prime_UTR 10298   10430   .       +       .       ID=LCD_CLX01G00001.1.V1.three_prime_UTR.1;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    three_prime_UTR 10504   10817   .       +       .       ID=LCD_CLX01G00001.1.V1.three_prime_UTR.2;Parent=LCD_CLX01G00001.1.V1;pacid=33123311
Chr1    phytozomev11    mRNA    2984    10562   .       +       .       ID=LCD_CLX01G00001.2.V1;Name=LCD_CLX01G00001.2;pacid=33123312;longest=0;Parent=LCD_CLX01G00001.V1
Chr1    phytozomev11    five_prime_UTR  2984    3255    .       +       .       ID=LCD_CLX01G00001.2.V1.five_prime_UTR.1;Parent=LCD_CLX01G00001.2.V1;pacid=33123312
Chr1    phytozomev11    five_prime_UTR  3354    3448    .       +       .       ID=LCD_CLX01G00001.2.V1.five_prime_UTR.2;Parent=LCD_CLX01G00001.2.V1;pacid=33123312
Chr1    phytozomev11    CDS     3449    3616    .       +       0       ID=LCD_CLX01G00001.2.V1.CDS.1;Parent=LCD_CLX01G00001.2.V1;pacid=33123312
Chr1    phytozomev11    CDS     4357    4455    .       +       0       ID=LCD_CLX01G00001.2.V1.CDS.2;Parent=LCD_CLX01G00001.2.V1;pacid=33123312
Chr1    phytozomev11    CDS     5457    5560    .       +       0       ID=LCD_CLX01G00001.2.V1.CDS.3;Parent=LCD_CLX01G00001.2.V1;pacid=33123312
Chr1    phytozomev11    CDS     7136    7944    .       +       1       ID=LCD_CLX01G00001.2.V1.CDS.4;Parent=LCD_CLX01G00001.2.V1;pacid=33123312
Chr1    phytozomev11    CDS     8028    8150    .       +       2       ID=LCD_CLX01G00001.2.V1.CDS.5;Parent=LCD_CLX01G00001.2.V1;pacid=33123312
Chr1    phytozomev11    CDS     8232    8320    .       +       2       ID=LCD_CLX01G00001.2.V1.CDS.6;Parent=LCD_CLX01G00001.2.V1;pacid=33123312
Chr1    phytozomev11    CDS     8408    8608    .       +       0       ID=LCD_CLX01G00001.2.V1.CDS.7;Parent=LCD_CLX01G00001.2.V1;pacid=33123312
Chr1    phytozomev11    CDS     9210    9311    .       +       0       ID=LCD_CLX01G00001.2.V1.CDS.8;Parent=LCD_CLX01G00001.2.V1;pacid=33123312
Chr1    phytozomev11    CDS     10104   10187   .       +       0       ID=LCD_CLX01G00001.2.V1.CDS.9;Parent=LCD_CLX01G00001.2.V1;pacid=33123312
Chr1    phytozomev11    CDS     10232   10244   .       +       0       ID=LCD_CLX01G00001.2.V1.CDS.10;Parent=LCD_CLX01G00001.2.V1;pacid=33123312
Chr1    phytozomev11    CDS     10504   10562   .       +       2       ID=LCD_CLX01G00001.2.V1.CDS.11;Parent=LCD_CLX01G00001.2.V1;pacid=33123312,

Thanks,
MK

**Comment by plantformatics** [comment]
Socrates assumes that the BED file is the collection of single-bp Tn5 insertion sites with strand information included (to allow for footprinting functions in future updates). However, strand isn't actually used by any functions at the moment - you can use "+" or "-" as a place holder in the fifth column. The expected columns are:

1. chromosome
2. start
3. end 
4. barcode
5. strand

Since Socrates expects the single-bp Tn5 insertion sites (for correct peak calling with MACS2 - using fragments will result in erroneous signal pileups), its best to extract the start and end coordinates to new lines. I just pushed an u update to adds an argument in the function `loadBEDandGenomeData` called `is.fragment` to specify if the provided BED file is a fragment.csv(.gz) from cellranger-atac. To use this option, simply set `is.fragment` to TRUE. The reason for the error is the lack of strand information in the fragment file which should be fixed if you set `is.fragment` to TRUE when loading your data into Socrates. This will require that you reinstall/update Socrates using install_github as written on the homepage of this repository. 

Alex
