### ISSUE TITLE
Segment fault when running regModel

### ISSUE THREAD

**Issue by cxfustc** [plantformatics/Socrates#4]
Hi, I ran Socrates in our data and got the segment fault when running regModel using default parameters:
  > obj <- regModel (obj, nthreads=1)
     |                                                                                          |  0%
  *** caught segfault ***
  address 0x7f2e3d1eaf10, cause 'memory not mapped'

  Tracback:
    1: (if (is.logical(from)) ..m2lgC else .m2dgC)(from)
    2: asMethod (object)
    3: as(from, "CsparseMatrix")
    4: asMethod(object)
    5: as(data, "sparseMatrix")
    6: Matrix(res, sparse=T)
    7: regMoel (obj, nthread=1)

How can I fix this?
Thanks very much

**Comment by plantformatics** [comment]
Can you let me know the result of these two commands?

`>dim(obj$counts)`
`>length(obj$counts@x)`

**Comment by cxfustc** [comment]
> dim (obj$counts)
[1] 932757   9122
> length(obj$counts@x)
[1] 21208781

**Comment by plantformatics** [comment]
`regModel` converts the sparse matrix into a dense one. You have nearly 1M sites with almost 10k cells. A dense matrix of that size cannot be stored in memory. I would recommend filtering sites down to < 100k with `cleanData` or using `tfidf` for normalization. The tutorial has more details on best practices for data processing

**Comment by cxfustc** [comment]
Thank you for your quick applies and suggestions!
I will try 'cleanDaa' and 'tfidf'.
