### ISSUE TITLE
Typo in loadBEDandGenomeData is.fragment option

### ISSUE THREAD

**Issue by IsaacDiaz026** [plantformatics/Socrates#7]
Hello, thank you for the awesome package!

I am having an issue when trying to use the loadBEDandGenomeData with the is.fragment=TRUE option. Here is the output.

Running pre-check on input files and executable paths ...
BED file path = /bigdata/seymourlab/idiaz026/Citrus_non-coding_evolution/2022-08-25_process_scATAC/Subset_ATAC_tn5_fragments.bed.gz ... ok
GFF file path = /bigdata/seymourlab/idiaz026/REFERENCES/Cclementina/Cclementina_scaff_genes.sort.gff.gz ... ok
Chromosome sizes file path = /bigdata/seymourlab/idiaz026/REFERENCES/Cclementina/Cclementina_genomeFile.txt ... ok
Macs2 is installed .... ok
 - loading data (this may take a while for big BED files) ...
 - converting fragment file to single-bp resolution Tn5 insertions sites ...
**Error in order(all.coordinates$V1, all.coordiantes$V2, decreasing = F) : 
  object 'all.coordiantes' not found**

I am pretty sure its just a typo in the all.coordinates, but I am unsure of where I should edit to fix this typo.

**Comment by plantformatics** [comment]
Not sure how we missed that, but the most recent branch should fix the issue. Let us know if you come across anything else!

Thanks, Alex.

**Comment by IsaacDiaz026** [comment]
Hi Alex,

Thanks for addressing this so quickly. I think I may have found one more typo in the loadBEDandGenomeData function with the is.fragment option.

In the section of code below you specify the end coordinates for the Tn5 bed file. I believe end.coordinates$V3 should be a$V3 rather than a$V2. This results in an IRanges error at the buildMetaData step of the tutorial.

Thanks again for this fantastic resource!

message(" - converting fragment file to single-bp resolution Tn5 insertions sites ...")
}
start.coordinates <- data.frame(V1 = a$V1, V2 = (a$V2),
V3 = (a$V2 + 1), V4 = a$V4, V5 = "+")
end.coordinates <- data.frame(V1 = a$V1, V2 = (a$V3 -
1), **V3 = a$V2,** V4 = a$V4, V5 = "-")

**Comment by plantformatics** [comment]
Fixed. You've probably already figured out that this is a function that we never use ;) 

Thanks for reporting these issues.
